### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_EndGame_160th.Altis#1]
- [x] Vorbereitungszeit einstellen
- [x] Version ohne Phase 1?
- [x] caching debug mode --> 0
- [x] Uhrzeit einstellen
- [x] Entfernung zur FOB überprüfen
- [x] Gruppenstruktur ändern --> mehr Slots?
- [x] mehr Fahrzeuge platzieren
- [x] Uniformenbilder in Thread

Nach Spiel:
- [x] committen

**Comment by McDiod** [comment]
## Skriptschnipsel:

**Loadout hat nicht funktioniert:**
`if (name player == "SPIELERNAME") then {[] call grad_loadout_fnc_applyloadout}`

**Spectator funktioniert nicht:**
`if (name player == "SPIELERNAME") then {[] call mcd_fnc_startSpectator}`

**Phase 1 überspringen:**
`if (isServer) then {["SkipToStage", [1]] call bis_fnc_moduleHVTObjectivesInstance}`

**Phase 2 überspringen:**
`if (isServer) then {MAXTIMETOENDGAME = 99999; ["SkipToStage", [2]] call bis_fnc_moduleHVTObjectivesInstance}`

**Caching töten:**
`[] call mcd_fnc_killZBE`

**Respawn funktioniert nicht:**
```
if (name player == "SPIELERNAME") then {
    [] spawn {
        _v1 = MAXRESPAWNTIME;
        _v2 = RESPAWNWAVESIZE;
        MAXRESPAWNTIME = 0;
        RESPAWNWAVESIZE = 999;
        sleep 5;
        MAXRESPAWNTIME = _v1;
        RESPAWNWAVESIZE = _v2;        
    };
};
``` 

**Respawn funktioniert immer noch nicht:**
```
if (name player == "SPIELERNAME") then {
    [] spawn {
        _v1 = MAXRESPAWNTIME;
        _v2 = RESPAWNWAVESIZE;
        MAXRESPAWNTIME = 0;
        RESPAWNWAVESIZE = 999;
        sleep 5;
        MAXRESPAWNTIME = _v1;
        RESPAWNWAVESIZE = _v2;
        setPlayerRespawnTime 0;
        forceRespawn player;
    };
};
```
